### ISSUE TITLE
Issue in running multisynth()

### ISSUE THREAD

**Issue by QLgogo** [ebenmichael/augsynth#35]
Hi Eli Ben-Michael,

Thanks for proposing a synthetic controls method for staggered adoption. I adapted the function: ppool_syn <- multisynth(lnppexpend ~ cbr, State, year, analysis_df, n_leads = 10) based on my dataset, which is a balance panel with staggered treatment time. But I encounter this error:

Error in cbind(wide$X, wide$y) : 
  number of rows of matrices must match (see arg 2)

I have no idea how to address this error. Any solution or suggestion are appreciated. Thanks.

**Comment by ebenmichael** [comment]
Hi, sorry for the delay. You might have `n_leads` set to be too large. In the example in the vignette it's set to 10, but if you can set it to something else. If you set that value too large then you'll get an error since you're asking to estimate treatment effects further out than you actually observe any data (e.g. if you have at most 5 post-treatment observations for each treated unit, setting `n_leads = 10` will break things). If that's not the issue, then I'll need some more info on your data to figure it out.

**Comment by spfleming** [comment]
I'm adding to this thread instead of starting a new issue; I'm having this problem as well, even if n_leads is NULL or set to 1.

**Comment by spfleming** [comment]
Specifically, I get a "subscript out of bounds" 

```
Error in Xc[[j]][, (dj - ndim + 1):dj, drop = F] : 
  subscript out of bounds
```

**Comment by ebenmichael** [comment]
I suspect this might have to do with a missing outcome at some time period. I just merged in a bunch of changes to the master branch that might help. Let me know if you still have problems.

**Comment by ahmedch92** [comment]
Hi,
So I am running multisynth for one my research projects and it is giving  the following error:

Error in Xc[[j]][, (dj - ndim + 1):dj, drop = F] : 
  subscript out of bounds

I know you have already addressed this issue in an earlier post as well, but I still cannot figure out a way around it.

Thanks in advance.
