### ISSUE TITLE
m of n bootstrap

### ISSUE THREAD

**Issue by jbayham** [ebenmichael/augsynth#36]
First, thanks for developing the package.  I'm using the multisynth routine to analyze a large number (2600) of treated units with staggered adoption.  I drop some suspect observations in the panel.  Not long after I submit the estimation command, R crashes.  After digging into the code a bit, I suspect the error occurs when the problem is sent to osqp.  When I keep the complete panel, R does not crash, but the problem is too large for my machine (144gb memory).  This latter issue provides an informative error and is not an issue with the package.  I wonder if there is a check that can be implemented before an incomplete panel is passed to osqp to prevent the crash?  

Because of the size of the problem, I have been estimating the model on subsets of the data and assessing the stability of the estimates.  It is computationally infeasible to apply the jackknife standard errors as you refer to in the paper and have coded in the package.  I am implementing an m-out-of-n bootstrap routine (https://stats.stackexchange.com/questions/33948/subsample-bootstrapping) for my case and would be happy to share.  Are you open to pull requests?  

Thank you again,

Jude

**Comment by ebenmichael** [comment]
Thanks for this! I'm actually working on a bunch of new changes in [this branch](https://github.com/ebenmichael/augsynth/tree/aux_cov_msyn) that should address part of this. 

First, I put in a workaround for unbalanced panels that looks for control units that have observed outcomes at the same time periods as the treated units. Second, I implemented a multiplier bootstrap approach that doesn't refit the weights, so that'll save a ton of computation and hopefully make inference with larger problems feasible.

If you're interested in trying out the branch, let me know if those new features are helpful to you. I'm open to a pull request for the bootstrap, although I imagine that also will have computational feasibility issues with larger datasets?

**Comment by ebenmichael** [comment]
Circling back to this, I just merged that branch into master, so lemme know if it helps with this issue! If not, happy to think through how to make it work.

**Comment by jbayham** [comment]
Finally getting back to this myself.  The updates solve my problem with the incomplete panel.  The current version returns a helpful error when the panel is incomplete and does not crash R.
