### ISSUE TITLE
Non-Convex Problem

### ISSUE THREAD

**Issue by mmbanasaz** [ebenmichael/augsynth#43]
Hi there
I have balanced panel data, contains 445 individuals and t = 10.
I am getting Non-convexity error with multisynth function:
"Error in KKT matrix LDL factorization when computing the nonzero elements. the problem seems to be non-convex."

I wondered if you have any idea what is going wrong.

**Comment by ebenmichael** [comment]
Are there multiple treated units or only one? Which function are you using?

Either way, what's probably happening is that you have enough units to get exact balance, and so will need to regularize the synthetic control by changing the `lambda` parameter.

**Comment by ebenmichael** [comment]
I dug into this a bit more since someone else ran into this problem too.

I think the issue is that you have a unit with only 1 pre-treatment time period, and are trying to both balance that outcome *and* demean it, which leads to a zero everywhere and a non-convex problem.

If that's the case, you're going to have to drop that unit
