### ISSUE TITLE
Error: cannot allocate vector of size 42.9 Gb

### ISSUE THREAD

**Issue by km-Poonacha** [ebenmichael/augsynth#52]
I have been trying to implement augsynth on my monthly-panel dataset, which has a staggard adoption of the treatment. The dataset size is as follows :

`Unbalanced Panel: n = 3609, T = 1-277, N = 45560`

When I try to run the model, with the code : 
`ppool_syn <- multisynth(outcome ~ treatment_status , project, month, data = data, fixedeff = T )`

i get the error : 

`cannot allocate vector of size 42.9 Gb. `

Is there a limit to the size of the dataset ? Or am I missing something ? 

I have not provided too much details of the project but will be happy to share more info if required. Thank you.

UPDATE:

I tried with a smaller data sample : 
`Unbalanced Panel: n = 1811, T = 1-129, N = 13230`

It seems to be able to run, but now it indicates that the problem is non-convex: 
`Error in KKT matrix LDL factorization when computing nonzero elements. The problem seems to be non-convexerror in osqp_setup: KKT matrix factorization `

**Comment by ebenmichael** [comment]
The error due to memory size is because there isn't 43 Gb of RAM to hold all the data, so you're running into memory issues. There's still some optimizing to do for memory usage, but I'm not sure that'll happen any time soon, or allow this to work for you here.


The other issue probably comes from missing values, which depends on the particular issues in your dataset. It could be, e.g. that some units have many missing values. I'd crack open the dataset and try it on balanced subsets to see where it breaks.
